# Generated by Django 4.1.1 on 2022-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', 'initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('selecao', models.CharField(max_length=30, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantia', models.FloatField()),
                ('categoria', models.CharField(choices=[('Comida e Bebida', 'Comida e Bebida'), ('Compras', 'Compras'), ('Habilitacao', 'Habilitacao'), ('Transporte', 'Transporte'), ('Veiculo', 'Veiculo'), ('Vida e Entretenimento', 'Vida e Entretenimento'), ('Comunicacao, PC', 'Comunicacao, PC'), ('Despesas Financeiras', 'Despesas Financeiras'), ('Investimentos', 'Investimentos'), ('Renda', 'Renda'), ('Outro', 'Outro')], max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
