# Generated by Django 4.1.1 on 2022-09-16 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_registry_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
