# Generated by Django 4.1.2 on 2022-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='descricao',
            field=models.CharField(max_length=275, null=True),
        ),
    ]
