# Generated by Django 4.1.2 on 2022-10-23 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investimento', models.CharField(max_length=40, null=True)),
                ('codigo_negociacao', models.CharField(max_length=40, null=True)),
                ('nome_fundo', models.CharField(max_length=50, null=True)),
                ('titulo_privado', models.CharField(max_length=50, null=True)),
                ('tipo_taxa', models.CharField(max_length=40, null=True)),
                ('taxa', models.FloatField()),
                ('taxa_adicional', models.FloatField()),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('data_vencimento', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('banco', models.CharField(max_length=40, null=True)),
                ('corretora', models.CharField(max_length=40, null=True)),
                ('quantidade', models.FloatField()),
                ('taxa_corretagem', models.FloatField()),
                ('outras_taxas', models.FloatField()),
                ('titulo_tesouro', models.CharField(max_length=50, null=True)),
                ('codigo_cetip', models.CharField(max_length=20, null=True)),
                ('codigo_debenture', models.CharField(max_length=20, null=True)),
                ('codigo_ativo_objeto', models.CharField(max_length=20, null=True)),
                ('codigo_coe', models.CharField(max_length=50, null=True)),
                ('moeda', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='repetir_senha',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='categoria',
            field=models.CharField(choices=[('Comida e Bebida', 'Comida e Bebida'), ('Compras', 'Compras'), ('Habilitacao', 'Habilitacao'), ('Transporte', 'Transporte'), ('Veiculo', 'Veiculo'), ('Vida e Entretenimento', 'Vida e Entretenimento'), ('Comunicacao, PC', 'Comunicacao, PC'), ('Despesas Financeiras', 'Despesas Financeiras'), ('Investimentos', 'Investimentos'), ('Renda', 'Renda'), ('Outro', 'Outro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='escolha',
            field=models.CharField(choices=[('Despesa', 'Despesa'), ('Receita', 'Receita')], default='Despesa', max_length=50, null=True),
        ),
    ]
