# Generated by Django 4.1.2 on 2022-10-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investments_login_repetir_senha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='codigo_negociacao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='investments',
            old_name='codigo_coe',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='codigo_ativo_objeto',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='codigo_cetip',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='codigo_debenture',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='investimento',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='moeda',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='nome_fundo',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='outras_taxas',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='taxa_adicional',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='tipo_taxa',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='titulo_privado',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='titulo_tesouro',
        ),
    ]
