# Generated by Django 4.1.2 on 2022-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_rename_codigo_negociacao_investments_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='quantidade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='taxa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='taxa_corretagem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='tipo',
            field=models.CharField(choices=[('Ações, BDR, ETFs, FIIs e Units', 'Ações, BDR, ETFs, FIIs e Units'), ('Fundos de Investimento', 'Fundos de Investimento'), ('Investimentos no Exterior', 'Investimentos no Exterior'), ('CDB / LCI / LCA / LC / LF', 'CDB / LCI / LCA / LC / LF'), ('CRI / CRA', 'CRI / CRA'), ('Debêntures', 'Debêntures'), ('Opções de Ações', 'Opções de Ações'), ('Termos de Ações', 'Termos de Ações'), ('Futuros', 'Futuros'), ('COE', 'COE'), ('Poupança', 'Poupança'), ('Moedas', 'Moedas'), ('Criptomoedas', 'Criptomoedas'), ('Ativos Genéricos', 'Ativos Genéricos'), ('Caixa', 'Caixa'), ('Commodities', 'Commodities')], max_length=50, null=True),
        ),
    ]
